set tabstop=4
set shiftwidth=4
set expandtab

set nocompatible
set ignorecase
set smartcase

colo default
syntax enable
filetype plugin indent on

set viminfo='50,<1000,s100,h

" colorise les nbsp
highlight NbSp ctermbg=lightgray guibg=lightred
match NbSp /\%xa0/
